### ISSUE TITLE
support of different jetson, any goals to support xavier/orin/etc.?

### ISSUE THREAD

**Issue by oak-tree** [Rubberazer/JETGPIO#8]

**Comment by Rubberazer** [comment]
No plan at this point, reason being that I don't have the hardware to test it and I don't like to release things completely untested.
So unless I come across some Orin or something by chance it will not happen, this is also unlikely because on my day job I don't play with this kind of hardware.
I basically created this lib because I got the nano for myself and the libraries available out there were not very enticing imo.
